//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yeniBingöl.Kaynak {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yeniBingöl.Kaynak.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Tarihi Zenginlikler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger1 {
            get {
                return ResourceManager.GetString("deger1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bingöl, tarihi zenginlikleriyle de öne çıkar. Zağ Mağaraları, Kral Kızı Kalesi ve tarihi köprüler, bölgenin geçmişine ışık tutar. Bu tarihi yapılar, Bingöl’ün binlerce yıllık mirasını gözler önüne serer.
        /// benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger2 {
            get {
                return ResourceManager.GetString("deger2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğal Güzellikler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger3 {
            get {
                return ResourceManager.GetString("deger3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bingöl, Türkiye’nin doğusunda yer alan ve doğal güzellikleriyle dikkat çeken bir şehirdir. Doğa severler için serin yaylalar, berrak göller ve etkileyici şelaleler sunar. Özellikle Çır Şelalesi ve Yüzen Ada, ziyaretçilerin hayranlığını kazanan önemli doğal cazibe merkezlerindendir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger4 {
            get {
                return ResourceManager.GetString("deger4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kültürel Miras benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger5 {
            get {
                return ResourceManager.GetString("deger5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bingöl, kültürel zenginlikleriyle de tanınır. Geleneksel Bingöl yemekleri, halk oyunları ve el sanatları, şehrin kültürel kimliğini yansıtır. Özellikle taş fırında yapılan tandır ekmeği ve sac kavurması, Bingöl mutfağının en özel lezzetlerindendir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string deger6 {
            get {
                return ResourceManager.GetString("deger6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string menu1 {
            get {
                return ResourceManager.GetString("menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nüfus ve İlçeler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string menu2 {
            get {
                return ResourceManager.GetString("menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih ve Turistik Yerler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string menu3 {
            get {
                return ResourceManager.GetString("menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string menu4 {
            get {
                return ResourceManager.GetString("menu4", resourceCulture);
            }
        }
    }
}
